#!/usr/bin/env node
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { root } from "./lib.mjs";
const required=["web/index.html","web/src/main.ts","web/src/App.vue","web/src/router.ts","web/src/views/ChannelsView.vue","web/src/views/ProvidersView.vue","web/src/views/AuthorizationView.vue","web/src/views/AccountsView.vue","web/src/views/SettingsView.vue","vite.config.ts","src/logging-settings.ts","src/usage-storage.ts","migrations/20260724_request_activity_5m.sql"];
const errors=[];
for(const file of required) if(!existsSync(join(root,file))) errors.push(`缺少 ${file}`);
const pkg=JSON.parse(readFileSync(join(root,"package.json"),"utf8"));
for(const dep of ["vue","naive-ui","pinia","vue-router"]) if(!pkg.dependencies?.[dep]) errors.push(`缺少前端依赖 ${dep}`);
const config=JSON.parse(readFileSync(join(root,"wrangler.jsonc"),"utf8"));
if(config.assets?.directory!=="./dist") errors.push("assets.directory 必须为 ./dist");
if(config.assets?.not_found_handling!=="single-page-application") errors.push("管理台必须启用 SPA fallback");
if(config.queues?.consumers?.[0]?.max_batch_size!==100||config.queues?.consumers?.[0]?.max_batch_timeout!==60) errors.push("聚合 Queue 必须使用 100 条 / 60 秒批处理上限");
const admin=readFileSync(join(root,"src/admin.ts"),"utf8");
if(admin.includes("ADMIN_SCRIPT")||admin.includes("ADMIN_CSS")||admin.includes("adminPage(")) errors.push("后端仍引用旧的内嵌管理页面");
if(!admin.includes('basePath("/admin")')) errors.push("管理 API 未挂载到 /admin");
const providers=readFileSync(join(root,"web/src/views/ProvidersView.vue"),"utf8");
if(!providers.includes("form.apiKey")||!providers.includes("首个 API Key")) errors.push("OpenAI-compatible 供应商表单缺少 API Key");
const authorization=readFileSync(join(root,"web/src/views/AuthorizationView.vue"),"utf8");
if(!authorization.includes("callbackUrl")||!authorization.includes("/exchange")) errors.push("Codex 管理台回调授权未接线");
const router=readFileSync(join(root,"web/src/router.ts"),"utf8");
if(!router.includes('path: "authorization"')||!router.includes("AuthorizationView.vue")) errors.push("独立授权页面未接入路由");
const accounts=readFileSync(join(root,"web/src/views/AccountsView.vue"),"utf8");
if(accounts.includes("添加账号 / API Key")||accounts.includes('api<{ data: Provider[] }>("/providers")')) errors.push("账号池仍暴露自定义供应商 API Key 管理入口");
if(!accounts.includes("近 2 小时健康状态")||!accounts.includes("stat-pill--success")||!accounts.includes("status-blocks")||!accounts.includes("发起授权")) errors.push("CPA 风格账号卡片、近两小时状态条或调用统计未接线");
const settings=readFileSync(join(root,"web/src/views/SettingsView.vue"),"utf8");
if(!settings.includes("requestLoggingEnabled")||!settings.includes("运行日志级别")||!settings.includes("5 分钟聚合")) errors.push("系统设置缺少请求日志开关、日志级别或聚合说明");
const worker=readFileSync(join(root,"src/index.ts"),"utf8");
if(!worker.includes("ACCOUNT_POOL_PROVIDER_IDS")||!worker.includes("provider_id IN")) errors.push("账号池分页接口未限制为内置渠道");
if(!worker.includes("request_activity_5m")||worker.includes("totalActivityResult")||!worker.includes("persistUsageQueueBatch")) errors.push("账号池与概览必须读取五分钟聚合表，禁止扫描全历史请求明细");
const proxy=readFileSync(join(root,"src/proxy-v2.ts"),"utf8");
if(proxy.includes("USAGE_QUEUE.send(usageEvent")||!proxy.includes("requestLoggingEnabled")||!proxy.includes('kind: "error"')) errors.push("成功请求不得逐条写入 Queue，失败明细必须受日志设置控制");
const limiter=readFileSync(join(root,"src/rate-limiter.ts"),"utf8");
if(!limiter.includes("activity_buckets")||!limiter.includes("setAlarm")||!limiter.includes('kind: "aggregate"')) errors.push("RateLimiter 未按五分钟桶聚合并通过 Queue 刷新");
const models=readFileSync(join(root,"web/src/views/ModelsView.vue"),"utf8");
if(!models.includes("groupedDiscovered")||!models.includes("支持端点")) errors.push("实际模型列表未按逻辑模型聚合端点");
const routes=readFileSync(join(root,"web/src/views/RoutesView.vue"),"utf8");
if(!routes.includes("managedGroups")||!routes.includes("endpointStates")) errors.push("供应商自动路由未聚合多协议端点");
const dashboard=readFileSync(join(root,"web/src/views/DashboardView.vue"),"utf8");
if(!dashboard.includes("heatmapRows")||!dashboard.includes("服务可用性热力图")) errors.push("概览热力图未接线");
if(errors.length){console.error(errors.map(v=>`✗ ${v}`).join("\n"));process.exit(1)}
console.log("✓ Vue 3 + Vite + Naive UI 管理台结构检查通过");
